// Metry. Wartości robocze przyjęte w rozmowie. height = wysokość głowy (dla Oblyra: grzbiet).
window.DRAGONS = [
  {name:'Abyrion', title:'Wielki Smok Grawitacji', category:'great', length:3400, height:1050, wingspan:4400, description:'Największy smok świata; w klatce piersiowej dawnej inkarnacji znajdowało się miasto.', silhouette:'assets/silhouettes/abyrion.webp'},
  {name:'Omnich', title:'Wielki Smok Mgły', category:'great', length:2850, height:820, wingspan:3600, description:'Smukły, z niezwykle długim ogonem.', silhouette:'assets/silhouettes/omnich.webp'},
  {name:'Vran', title:'Król Smoków · Wielki Smok Burzy', category:'great', length:2700, height:860, wingspan:3500, description:'Najpotężniejszy ze smoków; bardzo masywna budowa.', silhouette:'assets/silhouettes/vran.webp'},
  {name:'Fais', title:'Wielki Smok Ognia', category:'great', length:2680, height:845, wingspan:3450, description:'Rozmiarowo zbliżony do Vrana.', silhouette:'assets/silhouettes/fais.webp'},
  {name:'Ozyphar (dorosły)', title:'Wielki Smok Pustki', category:'great', length:2600, height:820, wingspan:3350, description:'Przewidywana dorosła forma.', silhouette:'assets/silhouettes/ozyphar-dorosly.webp'},
  {name:'Tyghala', title:'Królowa Smoków · Wielka Smoczyca Burzy', category:'great', length:2300, height:720, wingspan:3000, description:'Smuklejsza od Vrana.', silhouette:'assets/silhouettes/tyghala.webp'},
  {name:'Diafhotti', title:'Wielka Smoczyca Światła', category:'great', length:2200, height:690, wingspan:2880, description:'Budowa podobna do Tyghali.', silhouette:'assets/silhouettes/diafhotti.webp'},
  {name:'Saurous', title:'Wielki Smok Ciemności', category:'great', length:1950, height:610, wingspan:2550, description:'', silhouette:'assets/silhouettes/saurous.webp'},
  {name:'Ekhmides', title:'Wielki Smok Chaosu', category:'great', length:1900, height:595, wingspan:2480, description:'', silhouette:'assets/silhouettes/ekhmides.webp'},
  {name:'Stheryon', title:'Wielki Smok Stagnacji', category:'great', length:1550, height:500, wingspan:2050, description:'', silhouette:'assets/silhouettes/stheryon.webp'},
  {name:'Plimmya', title:'Wielka Smoczyca Oceanu', category:'great', length:1280, height:390, wingspan:1750, description:'Smukła wodna budowa.', silhouette:'assets/silhouettes/plimmya.webp'},
  {name:'Apoxil', title:'Wielki Smok Ziemi', category:'great', length:1240, height:550, wingspan:1700, description:'Czubek głowy osiąga wysokość grzbietu Abyriona.', silhouette:'assets/silhouettes/apoxil.webp'},
  {name:'Ripa', title:'Wielki Smok Płomieni Dusz', category:'great', length:1120, height:410, wingspan:1550, description:'Najmłodszy z Wielkich Smoków; smukły.', silhouette:'assets/silhouettes/ripa.webp'},
  {name:'Velyxar', title:'Wielki Smok Rozkładu', category:'great', length:1140, height:425, wingspan:1570, description:'Masywniejszy od Ripy; jeszcze się nie pojawił.', silhouette:'assets/silhouettes/velyxar.webp'},
  {name:'Asara', title:'Wyższa Smoczyca Burzy', category:'higher', length:340, height:105, wingspan:450, description:'Córka Vrana i Tyghali.', silhouette:'assets/silhouettes/asara.webp'},
  {name:'Ryghan', title:'Smocza forma', category:'dragon', length:250, height:78, wingspan:330, description:'Wnuk Asary.', silhouette:'assets/silhouettes/ryghan.webp'},
  {name:'Vaelor', title:'Smocza forma', category:'dragon', length:185, height:58, wingspan:245, description:'', silhouette:'assets/silhouettes/vaelor.webp'},
  {name:'Zwykły Smok Burzy', title:'Smok Burzy', category:'dragon', length:180, height:56, wingspan:240, description:'', silhouette:'assets/silhouettes/storm-regular.webp'},
  {name:'Thyssara', title:'Smok Oceanu', category:'dragon', length:168, height:48, wingspan:220, description:'', silhouette:'assets/silhouettes/thyssara.webp'},
  {name:'Ozyphar (nastoletni)', title:'Smok Pustki', category:'dragon', length:72, height:21, wingspan:88, description:'Młodsza forma Ozyphara.', silhouette:'assets/silhouettes/ozyphar-nastoletni.webp'},
  {name:'Ozyphar (dziecko)', title:'Smok Pustki', category:'dragon', length:1.8, height:0.9, wingspan:2.4, description:'Wielkość dużego psa.', silhouette:'assets/silhouettes/ozyphar-dziecko.webp'},
  {name:'Ozyphar (noworodek)', title:'Smok Pustki', category:'dragon', length:0.55, height:0.3, wingspan:0.75, description:'Najmłodsza forma.', silhouette:'assets/silhouettes/ozyphar-noworodek.webp'},
  {name:'Oblyr', title:'Drakonid Grawitacji', category:'drakonid', length:350, height:105, wingspan:null, description:'105 m do grzbietu, około 115 m do głowy.'},
  {name:'Thalass', title:'Drakonid Oceanu', category:'drakonid', length:155, height:43, wingspan:null, description:'Niemal tak długi jak Thyssara.'},
  {name:'Nullar', title:'Drakonid Pustki', category:'drakonid', length:105, height:32, wingspan:160, description:''},
  {name:'Hydra', title:'Drakonid Chaosu', category:'drakonid', length:75, height:28, wingspan:null, description:'Wielogłowa bestia.'},
  {name:'Wyrm', title:'Drakonid Ziemi', category:'drakonid', length:48, height:17, wingspan:null, description:''},
  {name:'Makria', title:'Drakonid Światła', category:'drakonid', length:32, height:12, wingspan:null, description:''},
  {name:'Stather', title:'Drakonid Stagnacji', category:'drakonid', length:22, height:8, wingspan:null, description:''},
  {name:'Psykhar', title:'Drakonid Płomieni Dusz', category:'drakonid', length:16, height:6, wingspan:32, description:''},
  {name:'Wyverna', title:'Drakonid Burzy', category:'drakonid', length:12, height:4.5, wingspan:24, description:''},
  {name:'Nyctheria', title:'Drakonid Ciemności', category:'drakonid', length:10, height:3.8, wingspan:20, description:''},
  {name:'Sarkyra', title:'Drakonid Rozkładu', category:'drakonid', length:8, height:3.2, wingspan:null, description:''},
  {name:'Drakia', title:'Drakonid Ognia', category:'drakonid', length:5.5, height:2, wingspan:7.5, description:'Głowa około 2 m nad ziemią.'},
  {name:'Anemis', title:'Drakonid Mgły', category:'drakonid', length:4.2, height:1.6, wingspan:null, description:'Głowa około 1,6 m nad ziemią.'}
].map((d,i)=>({id:i,...d}));
