// Jednostki: metry. Wymiary sa danymi, NIE sa wyliczane z ilustracji.
window.CREATURES = [
  {
    "name": "Abyrion",
    "title": "Wielki Smok Grawitacji",
    "category": "great",
    "length": 3400,
    "height": 1050,
    "wingspan": 4400,
    "description": "Największy smok świata; w klatce piersiowej dawnej inkarnacji znajdowało się miasto.",
    "silhouette": "assets/silhouettes/abyrion.webp",
    "id": 0,
    "kind": "creature",
    "tailFraction": 0.5,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#7566bb",
      "#382965",
      "#bba8ed"
    ]
  },
  {
    "name": "Omnich",
    "title": "Wielki Smok Mgły",
    "category": "great",
    "length": 2850,
    "height": 820,
    "wingspan": 3600,
    "description": "Smukły, z niezwykle długim ogonem.",
    "silhouette": "assets/silhouettes/omnich.webp",
    "id": 1,
    "kind": "creature",
    "tailFraction": 0.63,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#a1acb5",
      "#505c69",
      "#e2e9ec"
    ]
  },
  {
    "name": "Vran",
    "title": "Król Smoków · Wielki Smok Burzy",
    "category": "great",
    "length": 2700,
    "height": 860,
    "wingspan": 3500,
    "description": "Najpotężniejszy ze smoków; bardzo masywna budowa.",
    "silhouette": "assets/silhouettes/vran.webp",
    "id": 2,
    "kind": "creature",
    "tailFraction": 0.43,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#3679b2",
      "#163957",
      "#86dfff"
    ]
  },
  {
    "name": "Fais",
    "title": "Wielki Smok Ognia",
    "category": "great",
    "length": 2680,
    "height": 845,
    "wingspan": 3450,
    "description": "Rozmiarowo zbliżony do Vrana.",
    "silhouette": "assets/silhouettes/fais.webp",
    "id": 3,
    "kind": "creature",
    "tailFraction": 0.43,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#d14f2d",
      "#79221c",
      "#ffbd6c"
    ]
  },
  {
    "name": "Ozyphar (dorosły)",
    "title": "Wielki Smok Pustki",
    "category": "great",
    "length": 2600,
    "height": 820,
    "wingspan": 3350,
    "description": "Przewidywana dorosła forma.",
    "silhouette": "assets/silhouettes/ozyphar-dorosly.webp",
    "id": 4,
    "kind": "creature",
    "tailFraction": 0.5,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#7154a6",
      "#211b46",
      "#b88eff"
    ]
  },
  {
    "name": "Tyghala",
    "title": "Królowa Smoków · Wielka Smoczyca Burzy",
    "category": "great",
    "length": 2300,
    "height": 720,
    "wingspan": 3000,
    "description": "Smuklejsza od Vrana.",
    "silhouette": "assets/silhouettes/tyghala.webp",
    "id": 5,
    "kind": "creature",
    "tailFraction": 0.5,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#3679b2",
      "#163957",
      "#86dfff"
    ]
  },
  {
    "name": "Diafhotti",
    "title": "Wielka Smoczyca Światła",
    "category": "great",
    "length": 2200,
    "height": 690,
    "wingspan": 2880,
    "description": "Budowa podobna do Tyghali.",
    "silhouette": "assets/silhouettes/diafhotti.webp",
    "id": 6,
    "kind": "creature",
    "tailFraction": 0.5,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#e0d5a3",
      "#83795a",
      "#fff9d1"
    ]
  },
  {
    "name": "Saurous",
    "title": "Wielki Smok Ciemności",
    "category": "great",
    "length": 1950,
    "height": 610,
    "wingspan": 2550,
    "description": "",
    "silhouette": "assets/silhouettes/saurous.webp",
    "id": 7,
    "kind": "creature",
    "tailFraction": 0.5,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#464269",
      "#181324",
      "#887ca8"
    ]
  },
  {
    "name": "Ekhmides",
    "title": "Wielki Smok Chaosu",
    "category": "great",
    "length": 1900,
    "height": 595,
    "wingspan": 2480,
    "description": "",
    "silhouette": "assets/silhouettes/ekhmides.webp",
    "id": 8,
    "kind": "creature",
    "tailFraction": 0.5,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#793c93",
      "#301944",
      "#d58fff"
    ]
  },
  {
    "name": "Stheryon",
    "title": "Wielki Smok Stagnacji",
    "category": "great",
    "length": 1550,
    "height": 500,
    "wingspan": 2050,
    "description": "",
    "silhouette": "assets/silhouettes/stheryon.webp",
    "id": 9,
    "kind": "creature",
    "tailFraction": 0.5,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#bddbe2",
      "#5a8594",
      "#e8ffff"
    ]
  },
  {
    "name": "Plimmya",
    "title": "Wielka Smoczyca Oceanu",
    "category": "great",
    "length": 1280,
    "height": 390,
    "wingspan": 1750,
    "description": "Smukła wodna budowa.",
    "silhouette": "assets/silhouettes/plimmya.webp",
    "id": 10,
    "kind": "creature",
    "tailFraction": 0.57,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#3e99b1",
      "#155169",
      "#abe7ee"
    ]
  },
  {
    "name": "Apoxil",
    "title": "Wielki Smok Ziemi",
    "category": "great",
    "length": 1240,
    "height": 550,
    "wingspan": 1700,
    "description": "Czubek głowy osiąga wysokość grzbietu Abyriona.",
    "silhouette": "assets/silhouettes/apoxil.webp",
    "id": 11,
    "kind": "creature",
    "tailFraction": 0.5,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#8b7658",
      "#4e473b",
      "#cabb9d"
    ]
  },
  {
    "name": "Velyxar",
    "title": "Wielki Smok Rozkładu",
    "category": "great",
    "length": 1140,
    "height": 425,
    "wingspan": 1570,
    "description": "Masywniejszy od Ripy; jeszcze się nie pojawił.",
    "silhouette": "assets/silhouettes/velyxar.webp",
    "id": 12,
    "kind": "creature",
    "tailFraction": 0.5,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#aaafb5",
      "#4d5365",
      "#f6f9ff"
    ]
  },
  {
    "name": "Ripa",
    "title": "Wielki Smok Płomieni Dusz",
    "category": "great",
    "length": 1120,
    "height": 410,
    "wingspan": 1550,
    "description": "Najmłodszy z Wielkich Smoków; smukły.",
    "silhouette": "assets/silhouettes/ripa.webp",
    "id": 13,
    "kind": "creature",
    "tailFraction": 0.5,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#50a887",
      "#144e3f",
      "#a1f7a6"
    ]
  },
  {
    "name": "Asara",
    "title": "Wyższa Smoczyca Burzy",
    "category": "higher",
    "length": 340,
    "height": 105,
    "wingspan": 450,
    "description": "Córka Vrana i Tyghali.",
    "silhouette": "assets/silhouettes/asara.webp",
    "id": 14,
    "kind": "creature",
    "tailFraction": 0.5,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#3679b2",
      "#163957",
      "#86dfff"
    ]
  },
  {
    "name": "Ryghan",
    "title": "Smocza forma",
    "category": "dragon",
    "length": 180,
    "height": 52,
    "wingspan": 250,
    "description": "Wnuk Asary.",
    "silhouette": "assets/silhouettes/ryghan.webp",
    "id": 15,
    "kind": "creature",
    "tailFraction": 0.5,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#3679b2",
      "#163957",
      "#86dfff"
    ]
  },
  {
    "name": "Vaelor",
    "title": "Smocza forma",
    "category": "dragon",
    "length": 120,
    "height": 35,
    "wingspan": 170,
    "description": "",
    "silhouette": "assets/silhouettes/vaelor.webp",
    "id": 16,
    "kind": "creature",
    "tailFraction": 0.5,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#578fbb",
      "#2c4668",
      "#b1e0ff"
    ]
  },
  {
    "name": "Zwykły Smok Burzy",
    "title": "Smok Burzy",
    "category": "dragon",
    "length": 70,
    "height": 20,
    "wingspan": 100,
    "description": "",
    "silhouette": "assets/silhouettes/storm-regular.webp",
    "id": 17,
    "kind": "creature",
    "tailFraction": 0.5,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#3679b2",
      "#163957",
      "#86dfff"
    ]
  },
  {
    "name": "Thyssara",
    "title": "Smok Oceanu",
    "category": "dragon",
    "length": 65,
    "height": 19,
    "wingspan": 92,
    "description": "",
    "silhouette": "assets/silhouettes/thyssara.webp",
    "id": 18,
    "kind": "creature",
    "tailFraction": 0.57,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#3e99b1",
      "#155169",
      "#abe7ee"
    ]
  },
  {
    "name": "Ozyphar (nastoletni)",
    "title": "Smok Pustki",
    "category": "dragon",
    "length": 30,
    "height": 9,
    "wingspan": 44,
    "description": "Młodsza forma Ozyphara.",
    "silhouette": "assets/silhouettes/ozyphar-nastoletni.webp",
    "id": 19,
    "kind": "creature",
    "tailFraction": 0.5,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#7154a6",
      "#211b46",
      "#b88eff"
    ]
  },
  {
    "name": "Ozyphar (dziecko)",
    "title": "Smok Pustki",
    "category": "dragon",
    "length": 1.8,
    "height": 0.9,
    "wingspan": 2.4,
    "description": "Wielkość dużego psa.",
    "silhouette": "assets/silhouettes/ozyphar-dziecko.webp",
    "id": 20,
    "kind": "creature",
    "tailFraction": 0.5,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#7154a6",
      "#211b46",
      "#b88eff"
    ]
  },
  {
    "name": "Ozyphar (noworodek)",
    "title": "Smok Pustki",
    "category": "dragon",
    "length": 0.55,
    "height": 0.3,
    "wingspan": 0.75,
    "description": "Najmłodsza forma.",
    "silhouette": "assets/silhouettes/ozyphar-noworodek.webp",
    "id": 21,
    "kind": "creature",
    "tailFraction": 0.5,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#7154a6",
      "#211b46",
      "#b88eff"
    ]
  },
  {
    "name": "Oblyr",
    "title": "Drakonid Grawitacji",
    "category": "drakonid",
    "length": 350,
    "height": 105,
    "wingspan": null,
    "description": "105 m do grzbietu, około 115 m do głowy.",
    "silhouette": "assets/silhouettes/oblyr.webp",
    "id": 22,
    "kind": "creature",
    "tailFraction": 0.42,
    "figureKind": "armored",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#7566bb",
      "#382965",
      "#bba8ed"
    ]
  },
  {
    "name": "Hydra",
    "title": "Drakonid Chaosu",
    "category": "drakonid",
    "length": 75,
    "height": 28,
    "wingspan": null,
    "description": "Wielogłowa bestia.",
    "silhouette": "assets/silhouettes/hydra.webp",
    "id": 23,
    "kind": "creature",
    "tailFraction": 0.4,
    "figureKind": "hydra",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#793c93",
      "#301944",
      "#d58fff"
    ]
  },
  {
    "name": "Thalass",
    "title": "Drakonid Oceanu",
    "category": "drakonid",
    "length": 70,
    "height": 20,
    "wingspan": null,
    "description": "Drakonid Oceanu pozbawiony skrzydeł.",
    "silhouette": "assets/silhouettes/thalass.webp",
    "id": 24,
    "kind": "creature",
    "tailFraction": 0.57,
    "figureKind": "serpent",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#3e99b1",
      "#155169",
      "#abe7ee"
    ]
  },
  {
    "name": "Nullar",
    "title": "Drakonid Pustki",
    "category": "drakonid",
    "length": 50,
    "height": 14,
    "wingspan": 70,
    "description": "",
    "silhouette": "assets/silhouettes/nullar.webp",
    "id": 25,
    "kind": "creature",
    "tailFraction": 0.57,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#7154a6",
      "#211b46",
      "#b88eff"
    ]
  },
  {
    "name": "Wyrm",
    "title": "Drakonid Ziemi",
    "category": "drakonid",
    "length": 48,
    "height": 17,
    "wingspan": null,
    "description": "",
    "silhouette": "assets/silhouettes/wyrm.webp",
    "id": 26,
    "kind": "creature",
    "tailFraction": 0.57,
    "figureKind": "serpent",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#8b7658",
      "#4e473b",
      "#cabb9d"
    ]
  },
  {
    "name": "Makria",
    "title": "Drakonid Światła",
    "category": "drakonid",
    "length": 32,
    "height": 12,
    "wingspan": null,
    "description": "",
    "silhouette": "assets/silhouettes/makria.webp",
    "id": 27,
    "kind": "creature",
    "tailFraction": 0.57,
    "figureKind": "serpent",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#e0d5a3",
      "#83795a",
      "#fff9d1"
    ]
  },
  {
    "name": "Stather",
    "title": "Drakonid Stagnacji",
    "category": "drakonid",
    "length": 22,
    "height": 8,
    "wingspan": null,
    "description": "",
    "silhouette": "assets/silhouettes/stather.webp",
    "id": 28,
    "kind": "creature",
    "tailFraction": 0.57,
    "figureKind": "serpent",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#bddbe2",
      "#5a8594",
      "#e8ffff"
    ]
  },
  {
    "name": "Psykhar",
    "title": "Drakonid Płomieni Dusz",
    "category": "drakonid",
    "length": 16,
    "height": 6,
    "wingspan": 32,
    "description": "",
    "silhouette": "assets/silhouettes/psykhar.webp",
    "id": 29,
    "kind": "creature",
    "tailFraction": 0.52,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#50a887",
      "#144e3f",
      "#a1f7a6"
    ]
  },
  {
    "name": "Wyverna",
    "title": "Drakonid Burzy",
    "category": "drakonid",
    "length": 12,
    "height": 4.5,
    "wingspan": 24,
    "description": "",
    "silhouette": "assets/silhouettes/wyverna.webp",
    "id": 30,
    "kind": "creature",
    "tailFraction": 0.5,
    "figureKind": "wyvern",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#3679b2",
      "#163957",
      "#86dfff"
    ]
  },
  {
    "name": "Nyctheria",
    "title": "Drakonid Ciemności",
    "category": "drakonid",
    "length": 10,
    "height": 3.8,
    "wingspan": 20,
    "description": "",
    "silhouette": "assets/silhouettes/nyctheria.webp",
    "id": 31,
    "kind": "creature",
    "tailFraction": 0.5,
    "figureKind": "wyvern",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#464269",
      "#181324",
      "#887ca8"
    ]
  },
  {
    "name": "Sarkyra",
    "title": "Drakonid Rozkładu",
    "category": "drakonid",
    "length": 8,
    "height": 3.2,
    "wingspan": null,
    "description": "",
    "silhouette": "assets/silhouettes/sarkyra.webp",
    "id": 32,
    "kind": "creature",
    "tailFraction": 0.5,
    "figureKind": "quadruped",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#aaafb5",
      "#4d5365",
      "#f6f9ff"
    ]
  },
  {
    "name": "Drakia",
    "title": "Drakonid Ognia",
    "category": "drakonid",
    "length": 5.5,
    "height": 2,
    "wingspan": 7.5,
    "description": "Głowa około 2 m nad ziemią.",
    "silhouette": "assets/silhouettes/drakia.webp",
    "id": 33,
    "kind": "creature",
    "tailFraction": 0.5,
    "figureKind": "classic",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#d14f2d",
      "#79221c",
      "#ffbd6c"
    ]
  },
  {
    "name": "Anemis",
    "title": "Drakonid Mgły",
    "category": "drakonid",
    "length": 4.2,
    "height": 1.6,
    "wingspan": null,
    "description": "Głowa około 1,6 m nad ziemią.",
    "silhouette": "assets/silhouettes/anemis.png",
    "id": 34,
    "kind": "creature",
    "tailFraction": 0.53,
    "figureKind": "biped",
    "art_note": "Schemat kalibracyjny oparty na wymiarach; zachowana ilustracja oryginalna jest pokazana po kliknięciu.",
    "palette": [
      "#a1acb5",
      "#505c69",
      "#e2e9ec"
    ]
  }
];
window.REFERENCE_ITEMS = [
  {
    "id": "ref-human",
    "name": "Przeciętny człowiek",
    "title": "Reference item",
    "category": "reference",
    "length": 0.5,
    "height": 1.75,
    "wingspan": null,
    "description": "Przeciętny dorosły człowiek: 1,75 m wysokości.",
    "silhouette": "assets/references/human.png",
    "kind": "reference",
    "measurementNote": "Wymiary orientacyjne obiektu porównawczego.",
    "calibratedArtwork": "assets/references-cropped/human.webp",
    "artRatio": 0.345688
  },
  {
    "id": "ref-sedan",
    "name": "Samochód osobowy",
    "title": "Reference item",
    "category": "reference",
    "length": 4.5,
    "height": 1.45,
    "wingspan": null,
    "description": "Typowy sedan klasy średniej.",
    "silhouette": "assets/references/sedan.png",
    "kind": "reference",
    "measurementNote": "Wymiary orientacyjne obiektu porównawczego.",
    "calibratedArtwork": "assets/references-cropped/sedan.webp",
    "artRatio": 3.136842
  },
  {
    "id": "ref-giraffe",
    "name": "Żyrafa",
    "title": "Reference item",
    "category": "reference",
    "length": 3.5,
    "height": 5.5,
    "wingspan": null,
    "description": "Dorosła żyrafa.",
    "silhouette": "assets/references/giraffe.png",
    "kind": "reference",
    "measurementNote": "Wymiary orientacyjne obiektu porównawczego.",
    "calibratedArtwork": "assets/references-cropped/giraffe.webp",
    "artRatio": 0.650847
  },
  {
    "id": "ref-bus",
    "name": "Autobus miejski",
    "title": "Reference item",
    "category": "reference",
    "length": 12,
    "height": 3.2,
    "wingspan": null,
    "description": "Standardowy 12-metrowy autobus.",
    "silhouette": "assets/references/bus.png",
    "kind": "reference",
    "measurementNote": "Wymiary orientacyjne obiektu porównawczego.",
    "calibratedArtwork": "assets/references-cropped/bus.webp",
    "artRatio": 3.481481
  },
  {
    "id": "ref-trex",
    "name": "Tyranozaur rex",
    "title": "Reference item",
    "category": "reference",
    "length": 12,
    "height": 4,
    "wingspan": null,
    "description": "Około 12 m od pyska do końca ogona; wysokość przybliżona.",
    "silhouette": "assets/references/trex.png",
    "kind": "reference",
    "measurementNote": "Wymiary orientacyjne obiektu porównawczego.",
    "calibratedArtwork": "assets/references-cropped/trex.webp",
    "artRatio": 2.202605
  },
  {
    "id": "ref-bluewhale",
    "name": "Płetwal błękitny",
    "title": "Reference item",
    "category": "reference",
    "length": 27,
    "height": 5.2,
    "wingspan": null,
    "description": "Największe współczesne zwierzę.",
    "silhouette": "assets/references/bluewhale.png",
    "kind": "reference",
    "measurementNote": "Wymiary orientacyjne obiektu porównawczego.",
    "calibratedArtwork": "assets/references-cropped/bluewhale.webp",
    "artRatio": 4.928571
  },
  {
    "id": "ref-apartment",
    "name": "10-piętrowy blok",
    "title": "Reference item",
    "category": "reference",
    "length": 28,
    "height": 30,
    "wingspan": null,
    "description": "Uproszczony apartamentowiec 10-kondygnacyjny.",
    "silhouette": "assets/references/apartment.png",
    "kind": "reference",
    "measurementNote": "Wymiary orientacyjne obiektu porównawczego.",
    "calibratedArtwork": "assets/references-cropped/apartment.webp",
    "artRatio": 0.584388
  },
  {
    "id": "ref-jumbojet",
    "name": "Boeing 747-8",
    "title": "Reference item",
    "category": "reference",
    "length": 76.3,
    "height": 19.4,
    "wingspan": 68.4,
    "description": "Długość 76,3 m, rozpiętość skrzydeł około 68,4 m.",
    "silhouette": "assets/references/jumbojet.png",
    "kind": "reference",
    "measurementNote": "Wymiary orientacyjne obiektu porównawczego.",
    "calibratedArtwork": "assets/references-cropped/jumbojet.webp",
    "artRatio": 3.965699
  },
  {
    "id": "ref-statue",
    "name": "Statua Wolności",
    "title": "Reference item",
    "category": "reference",
    "length": 18.3,
    "height": 93,
    "wingspan": null,
    "description": "93 m wraz z cokołem.",
    "silhouette": "assets/references/statue-liberty.png",
    "kind": "reference",
    "measurementNote": "Wymiary orientacyjne obiektu porównawczego.",
    "calibratedArtwork": "assets/references-cropped/statue-liberty.webp",
    "artRatio": 0.29776
  },
  {
    "id": "ref-field",
    "name": "Boisko piłkarskie",
    "title": "Reference item",
    "category": "reference",
    "length": 105,
    "height": 0,
    "wingspan": null,
    "description": "Boisko piłkarskie 105 × 68 m w rzucie z góry. Nie porównujemy jego wysokości.",
    "silhouette": "assets/references/football-field.png",
    "kind": "reference",
    "measurementNote": "Wymiary orientacyjne obiektu porównawczego.",
    "calibratedArtwork": "assets/references-cropped/football-field.webp",
    "artRatio": 1.664251
  },
  {
    "id": "ref-pyramid",
    "name": "Wielka Piramida w Gizie",
    "title": "Reference item",
    "category": "reference",
    "length": 230.4,
    "height": 138.5,
    "wingspan": null,
    "description": "Dzisiejsza wysokość około 138,5 m; pierwotna wynosiła około 146,6 m. Długość boku podstawy około 230,4 m.",
    "silhouette": "assets/references/pyramid.png",
    "kind": "reference",
    "measurementNote": "Wymiary orientacyjne obiektu porównawczego.",
    "calibratedArtwork": "assets/references-cropped/pyramid.webp",
    "artRatio": 1.818066
  },
  {
    "id": "ref-pkin",
    "name": "Pałac Kultury i Nauki",
    "title": "Reference item",
    "category": "reference",
    "length": 53,
    "height": 237,
    "wingspan": null,
    "description": "Warszawski PKiN.",
    "silhouette": "assets/references/pkin.png",
    "kind": "reference",
    "measurementNote": "Wymiary orientacyjne obiektu porównawczego.",
    "calibratedArtwork": "assets/references-cropped/pkin.webp",
    "artRatio": 0.664452
  },
  {
    "id": "ref-eiffel",
    "name": "Wieża Eiffla",
    "title": "Reference item",
    "category": "reference",
    "length": 125,
    "height": 330,
    "wingspan": null,
    "description": "Wysokość z antenami około 330 m.",
    "silhouette": "assets/references/eiffel.png",
    "kind": "reference",
    "measurementNote": "Wymiary orientacyjne obiektu porównawczego.",
    "calibratedArtwork": "assets/references-cropped/eiffel.webp",
    "artRatio": 0.557866
  },
  {
    "id": "ref-burj",
    "name": "Burj Khalifa",
    "title": "Reference item",
    "category": "reference",
    "length": 162,
    "height": 828,
    "wingspan": null,
    "description": "828 m całkowitej wysokości. Szerokość budynku na wizualizacji jest wyłącznie poglądowa.",
    "silhouette": "assets/references/burj.png",
    "kind": "reference",
    "measurementNote": "Wymiary orientacyjne obiektu porównawczego.",
    "calibratedArtwork": "assets/references-cropped/burj.webp",
    "artRatio": 0.266854
  },
  {
    "id": "ref-everest",
    "name": "Mount Everest",
    "title": "Reference item",
    "category": "reference",
    "length": null,
    "height": 8848.86,
    "wingspan": null,
    "description": "8848,86 m to wysokość szczytu nad poziomem morza, NIE wysokość góry od podnóża. Nie prezentujemy go jako bryły wysokiej na 8848,86 m.",
    "silhouette": "assets/references/everest.png",
    "kind": "reference",
    "measurementNote": "Wymiary orientacyjne obiektu porównawczego.",
    "elevationOnly": true,
    "calibratedArtwork": "assets/references-cropped/everest.webp",
    "artRatio": 1.973901
  }
];
