// Metry. Wartości robocze przyjęte w rozmowie. height = wysokość głowy (dla Oblyra: grzbiet).
window.DRAGONS = [
['Abyrion','Wielki Smok Grawitacji','great',3400,1050,4400,'Największy smok świata; w klatce piersiowej dawnej inkarnacji znajdowało się miasto.'],
['Omnich','Wielki Smok Mgły','great',2850,820,3600,'Smukły, z niezwykle długim ogonem.'],
['Vran','Król Smoków · Wielki Smok Burzy','great',2700,860,3500,'Najpotężniejszy ze smoków; bardzo masywna budowa.'],
['Fais','Wielki Smok Ognia','great',2680,845,3450,'Rozmiarowo zbliżony do Vrana.'],
['Ozyphar (dorosły)','Wielki Smok Pustki','great',2600,820,3350,'Przewidywana dorosła forma.'],
['Tyghala','Królowa Smoków · Wielka Smoczyca Burzy','great',2300,720,3000,'Smuklejsza od Vrana.'],
['Diafhotti','Wielka Smoczyca Światła','great',2200,690,2880,'Budowa podobna do Tyghali.'],
['Saurous','Wielki Smok Ciemności','great',1950,610,2550,''],
['Ekhmides','Wielki Smok Chaosu','great',1900,595,2480,''],
['Stheryon','Wielki Smok Stagnacji','great',1550,500,2050,''],
['Plimmya','Wielka Smoczyca Oceanu','great',1280,390,1750,'Smukła wodna budowa.'],
['Apoxil','Wielki Smok Ziemi','great',1240,550,1700,'Czubek głowy osiąga wysokość grzbietu Abyriona.'],
['Ripa','Wielki Smok Płomieni Dusz','great',1120,410,1550,'Najmłodszy z Wielkich Smoków; smukły.'],
['Velyxar','Wielki Smok Rozkładu','great',1140,425,1570,'Masywniejszy od Ripy; jeszcze się nie pojawił.'],
['Asara','Wyższa Smoczyca Burzy','higher',340,105,450,'Córka Vrana i Tyghali.'],
['Ryghan','Smocza forma','dragon',250,78,330,'Wnuk Asary.'],
['Vaelor','Smocza forma','dragon',185,58,245,''],
['Zwykły Smok Burzy','Smok Burzy','dragon',180,56,240,''],
['Thyssara','Smok Oceanu','dragon',168,48,220,''],
['Ozyphar (nastoletni)','Smok Pustki','dragon',72,21,95,'Młodsza forma Ozyphara.'],
['Ozyphar (dziecko)','Smok Pustki','dragon',1.8,.9,2.4,'Wielkość dużego psa.'],
['Ozyphar (noworodek)','Smok Pustki','dragon',.55,.3,.75,'Najmłodsza forma.'],
['Oblyr','Drakonid Grawitacji','drakonid',350,105,null,'105 m do grzbietu, około 115 m do głowy.'],
['Thalass','Drakonid Oceanu','drakonid',155,43,null,'Niemal tak długi jak Thyssara.'],
['Nullar','Drakonid Pustki','drakonid',105,32,160,''],
['Hydra','Drakonid Chaosu','drakonid',75,28,null,'Wielogłowa bestia.'],
['Wyrm','Drakonid Ziemi','drakonid',48,17,null,''],
['Makria','Drakonid Światła','drakonid',32,12,null,''],
['Stather','Drakonid Stagnacji','drakonid',22,8,null,''],
['Psykhar','Drakonid Płomieni Dusz','drakonid',16,6,80,''],
['Wyverna','Drakonid Burzy','drakonid',12,4.5,73,''],
['Nyctheria','Drakonid Ciemności','drakonid',10,3.8,64,''],
['Sarkyra','Drakonid Rozkładu','drakonid',8,3.2,null,''],
['Drakia','Drakonid Ognia','drakonid',5.5,2,7.5,'Głowa około 2 m nad ziemią.'],
['Anemis','Drakonid Mgły','drakonid',4.2,1.6,null,'Głowa około 1,6 m nad ziemią.']
].map(([name,title,category,length,height,wingspan,description],i)=>({id:i,name,title,category,length,height,wingspan,description}));
